"""Type stubs for the compiled layer (src/lib.rs). The public API is cufsm/__init__.py, which is
typed inline; these cover what it calls."""

from typing import Dict, List, Optional, Tuple

_Rows = List[List[float]]
_Arrays = Tuple[_Rows, _Rows, _Rows, _Rows, _Rows]  # prop, node, elem, constraints, springs
_Row = Tuple[float, List[float], List[float], List[List[float]]]  # length, m_terms, lfs, modes

class MechanismError(ValueError): ...

def section_properties(arrays: _Arrays) -> Dict[str, object]: ...
def stress(arrays: _Arrays, p: float, mxx: float, mzz: float, m11: float, m22: float, b: float,
           unsymmetric: bool) -> List[float]: ...
def first_yield(arrays: _Arrays, fy: float, unsymmetric: bool, extreme_fibre: bool) -> Dict[str, float]: ...
def stress_to_action(arrays: _Arrays) -> Dict[str, float]: ...
def strip(arrays: _Arrays, lengths: List[float], m_all: List[List[float]], bc: str, neigs: int,
          spaces: Optional[str] = None) -> List[_Row]: ...
def signature(arrays: _Arrays, lengths: Optional[List[float]], neigs: int
              ) -> Tuple[List[_Row], List[Tuple[float, float]]]: ...
def classify(arrays: _Arrays, results: List[_Row], bc: str, orth: str, norm: str, ospace: str
             ) -> List[List[Tuple[float, float, float, float]]]: ...
def template(shape: str, h: float, b1: float, b2: float, d1: float, d2: float, r1: float, r2: float,
             r3: float, r4: float, q1: float, q2: float, t: float, nh: int, nb1: int, nb2: int,
             nd1: int, nd2: int, nr1: int, nr2: int, nr3: int, nr4: int, centerline: bool
             ) -> Tuple[_Rows, _Rows]: ...
